[package]
name = "release_channel"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[dependencies]
gpui.workspace = true
workspace-hack = { version = "0.1", path = "../workspace-hack" }
