# This file contains settings for `cargo hakari`.
# See https://docs.rs/cargo-hakari/latest/cargo_hakari/config for a full list of options.

hakari-package = "workspace-hack"

resolver = "2"
dep-format-version = "4"

platforms = [
    # "x86_64-unknown-linux-gnu",
    # "x86_64-apple-darwin",
    # "aarch64-apple-darwin",
    # "x86_64-pc-windows-msvc",
]
